# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
full_AUC <- function(tt_0, tt_1) {
    .Call(`_optcombVUS_full_AUC`, tt_0, tt_1)
}

#' @export
auc_C_smooth <- function(tt1, tt2, h, link) {
    .Call(`_optcombVUS_auc_C_smooth`, tt1, tt2, h, link)
}

#' @export
vusC_full <- function(tt1, tt2, tt3) {
    .Call(`_optcombVUS_vusC_full`, tt1, tt2, tt3)
}

#' @export
vusC_sigmoid <- function(tt1, tt2, tt3, sig_n) {
    .Call(`_optcombVUS_vusC_sigmoid`, tt1, tt2, tt3, sig_n)
}

#' @export
vusC_probit <- function(tt1, tt2, tt3, sig_n) {
    .Call(`_optcombVUS_vusC_probit`, tt1, tt2, tt3, sig_n)
}

